//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCipher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenCipher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .aes.
        /// </summary>
        internal static string AesFileExtension {
            get {
                return ResourceManager.GetString("AesFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .asc.
        /// </summary>
        internal static string AscFileExtension {
            get {
                return ResourceManager.GetString("AscFileExtension", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Clipboard {
            get {
                object obj = ResourceManager.GetObject("Clipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content of the clipboard does not seem to be encrypted data..
        /// </summary>
        internal static string ClipboardContentErrorMessage {
            get {
                return ResourceManager.GetString("ClipboardContentErrorMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ClipboardLock {
            get {
                object obj = ResourceManager.GetObject("ClipboardLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClipboardUnlock {
            get {
                object obj = ResourceManager.GetObject("ClipboardUnlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt clipboard.
        /// </summary>
        internal static string DecryptClipboardMessage {
            get {
                return ResourceManager.GetString("DecryptClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt {0}.
        /// </summary>
        internal static string DecryptFileMessage {
            get {
                return ResourceManager.GetString("DecryptFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt file.
        /// </summary>
        internal static string DecryptFileTitle {
            get {
                return ResourceManager.GetString("DecryptFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt selected text.
        /// </summary>
        internal static string DecryptSelectionMessage {
            get {
                return ResourceManager.GetString("DecryptSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files|*.
        /// </summary>
        internal static string DialogFilterAllFiles {
            get {
                return ResourceManager.GetString("DialogFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done !.
        /// </summary>
        internal static string DoneMessage {
            get {
                return ResourceManager.GetString("DoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard is empty.
        /// </summary>
        internal static string EmptyClipboardErrorMessage {
            get {
                return ResourceManager.GetString("EmptyClipboardErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt clipboard.
        /// </summary>
        internal static string EncryptClipboardMessage {
            get {
                return ResourceManager.GetString("EncryptClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt {0}.
        /// </summary>
        internal static string EncryptFileMessage {
            get {
                return ResourceManager.GetString("EncryptFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt file.
        /// </summary>
        internal static string EncryptFileTitle {
            get {
                return ResourceManager.GetString("EncryptFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt selected text.
        /// </summary>
        internal static string EncryptSelectionMessage {
            get {
                return ResourceManager.GetString("EncryptSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap File {
            get {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon FileAesIcon {
            get {
                object obj = ResourceManager.GetObject("FileAesIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon FileAscIcon {
            get {
                object obj = ResourceManager.GetObject("FileAscIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\Open Cipher]
        ///@=&quot;Encrypt using Open Cipher&quot;
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\Open Cipher\command]
        ///@=&quot;\&quot;[[OPEN_CIPHER_EXE]]\&quot; \&quot;%1\&quot;&quot;
        ///
        ///
        ///[HKEY_CLASSES_ROOT\.asc]
        ///@=&quot;AES encrypted file&quot;
        ///
        ///[HKEY_CLASSES_ROOT\.asc\DefaultIcon]
        ///@=&quot;[[OPEN_CIPHER_ASC_ICO]],0&quot;
        ///
        ///[HKEY_CLASSES_ROOT\.asc\shell]
        ///@=&quot;decrypt&quot;
        ///
        ///[HKEY_CLASSES_ROOT\.asc\shell\decrypt]
        ///@=&quot;&amp;Decrypt&quot;
        ///
        ///[HKEY_CLASSES_ROOT\.asc\shell\decrypt\command]
        ///@=&quot;\&quot;[[OPEN_CIPHER_EXE]]\&quot; \&quot;%1\&quot;&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileAssociationsRegFile {
            get {
                return ResourceManager.GetString("FileAssociationsRegFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been decrypted to {0}..
        /// </summary>
        internal static string FileDecryptedToMessage {
            get {
                return ResourceManager.GetString("FileDecryptedToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been encrypted to {0}..
        /// </summary>
        internal static string FileEncryptedToMessage {
            get {
                return ResourceManager.GetString("FileEncryptedToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been encrypted to {0} using base 64 encoding..
        /// </summary>
        internal static string FileEncryptedToUsingBase64Message {
            get {
                return ResourceManager.GetString("FileEncryptedToUsingBase64Message", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FileLock {
            get {
                object obj = ResourceManager.GetObject("FileLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileTxt {
            get {
                object obj = ResourceManager.GetObject("FileTxt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileTxtLock {
            get {
                object obj = ResourceManager.GetObject("FileTxtLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileTxtUnlock {
            get {
                object obj = ResourceManager.GetObject("FileTxtUnlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileUnlock {
            get {
                object obj = ResourceManager.GetObject("FileUnlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.htm.
        /// </summary>
        internal static string HelpFile {
            get {
                return ResourceManager.GetString("HelpFile", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LockClosed {
            get {
                object obj = ResourceManager.GetObject("LockClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon LockClosedIcon {
            get {
                object obj = ResourceManager.GetObject("LockClosedIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LockOpen {
            get {
                object obj = ResourceManager.GetObject("LockOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon LockOpenIcon {
            get {
                object obj = ResourceManager.GetObject("LockOpenIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Cipher.
        /// </summary>
        internal static string OpenCipherTitle {
            get {
                return ResourceManager.GetString("OpenCipherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to openssl.exe.
        /// </summary>
        internal static string OpenSslBinary {
            get {
                return ResourceManager.GetString("OpenSslBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong key..
        /// </summary>
        internal static string WrongKeyErrorMessage {
            get {
                return ResourceManager.GetString("WrongKeyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong magic number. Maybe you could try to check process base 64 box..
        /// </summary>
        internal static string WrongMagicNumberErrorMessage {
            get {
                return ResourceManager.GetString("WrongMagicNumberErrorMessage", resourceCulture);
            }
        }
    }
}
